### PR TITLE
feat: store msg types inside `message_type` table and add `messages_by_type` function

### PR DESCRIPTION
**Pull request by MonikaCat**
## Description

Changes:
- Stored messages types inside new `message_type` table 
- Added new `messages_by_type` function
- Added `v5` migrator to parse all msg types already stored in db

## Checklist
- [x] Targeted PR against correct branch.
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.  
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by rmontagnin** [comment]
I don't undestand: why is this necessary? Which use cases does it solve?

**Comment by MonikaCat** [comment]
Hey @RiccardoM sure let me explain it a bit, so it's part of [BDU-1150](https://forbole.atlassian.net/browse/BDU-1150) issue, we want to allow users to filter the transactions by type on big dipper. I added new `message_type` table so we can quickly retrieve available msg types for each chain to display on big dipper. This will also help us to fix the message labels on big dipper as right now they are all hardcoded on the FE 

[BDU-1150]: https://forbole.atlassian.net/browse/BDU-1150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by rmontagnin** [comment]
@MonikaCat I don't believe this is something that should be done inside Juno. Instead, it should be done inside BDJuno since it is something that is custom to BigDipepr and not something that all parsers want to have. For example, Athena (DJuno) does not care about messages types. I would prefer we keep Juno as feature-agnostic as possible, moving all custom parsing logic into BDJuno or other parsers.

**Comment by MonikaCat** [comment]
@RiccardoM ok I will move it to BDJuno, thanks 👍🏻

**Pull request closed without merging**
